### ISSUE TITLE
Error.captureStackTrace(err, this) / cause: ConnectTimeoutError: Connect Timeout Error

### ISSUE THREAD

**Issue by PublicWorld** [goenning/google-indexing-script#17]
Hi, I got this error when I started executing the `npm run index mywebsite`
```
node:internal/deps/undici/undici:11576
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchRetry (file:///Users/jack/Desktop/google-indexing-script/src/shared/utils.mjs:14:22)
    at async getSitemapsList (file:///Users/jack/Desktop/google-indexing-script/src/shared/sitemap.mjs:9:20)
    at async getSitemapPages (file:///Users/jack/Desktop/google-indexing-script/src/shared/sitemap.mjs:33:20)
    at async file:///Users/jack/Desktop/google-indexing-script/src/index.mjs:27:27 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:8522:28)
      at node:internal/deps/undici/undici:8480:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:8511:13)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

```
<img width="832" alt="image" src="https://github.com/goenning/google-indexing-script/assets/12987627/9c1a2932-e1aa-4489-b628-21635259d996">

**Comment by goenning** [comment]
It’s a timeout / network error, nothing we can do on the script
