### ISSUE TITLE
throw new Error('No key or keyFile set.')

### ISSUE THREAD

**Issue by dev-coco** [goenning/google-indexing-script#19]
```Shell
/Users/raz1ner/Downloads/google-indexing-script/node_modules/gtoken/build/src/index.js:148
            throw new Error('No key or keyFile set.');
                  ^

Error: No key or keyFile set.
    at GoogleToken.getTokenAsyncInner (/Users/raz1ner/Downloads/google-indexing-script/node_modules/gtoken/build/src/index.js:148:19)
    at GoogleToken.getTokenAsync (/Users/raz1ner/Downloads/google-indexing-script/node_modules/gtoken/build/src/index.js:137:55)
    at GoogleToken.getToken (/Users/raz1ner/Downloads/google-indexing-script/node_modules/gtoken/build/src/index.js:96:21)
    at JWT.refreshTokenNoCache (/Users/raz1ner/Downloads/google-indexing-script/node_modules/google-auth-library/build/src/auth/jwtclient.js:165:36)
    at JWT.refreshToken (/Users/raz1ner/Downloads/google-indexing-script/node_modules/google-auth-library/build/src/auth/oauth2client.js:143:25)
    at JWT.authorizeAsync (/Users/raz1ner/Downloads/google-indexing-script/node_modules/google-auth-library/build/src/auth/jwtclient.js:146:35)
    at JWT.authorize (/Users/raz1ner/Downloads/google-indexing-script/node_modules/google-auth-library/build/src/auth/jwtclient.js:142:25)
    at getAccessToken (file:///Users/raz1ner/Downloads/google-indexing-script/src/shared/auth.mjs:20:34)
    at file:///Users/raz1ner/Downloads/google-indexing-script/src/index.mjs:22:27
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
 ```

**Comment by goenning** [comment]
Seems like there's something wrong with your service_account.json file. it should look like this:

```json
{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "...",
  "client_email": "...",
  "client_id": "...",
  "auth_uri": "...",
  "token_uri": "...",
  "auth_provider_x509_cert_url": "...",
  "client_x509_cert_url": "...",
  "universe_domain": "googleapis.com"
}
```
