### ISSUE TITLE
Error: error:1E08010C:DECODER routines::unsupported

### ISSUE THREAD

**Issue by deepakmahakale** [goenning/google-indexing-script#77]
I am trying to run this using the ENV variable approach as I am running this on GitHub action

```bash
GIS_CLIENT_EMAIL="deepak****iam.gserviceaccount.com" GIS_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMbQk**************4=\n-----END PRIVATE KEY-----\n" gis mywebsite.com
```

```log
node:internal/crypto/sig:131
  const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
                            ^

Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/Users/deepak/workspace/personal/google-indexing-script/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/Users/deepak/workspace/personal/google-indexing-script/node_modules/jws/lib/sign-stream.js:32:24)
    at GoogleToken.requestToken (/Users/deepak/workspace/personal/google-indexing-script/node_modules/gtoken/build/src/index.js:224:31)
    at GoogleToken.getTokenAsyncInner (/Users/deepak/workspace/personal/google-indexing-script/node_modules/gtoken/build/src/index.js:158:21)
    at GoogleToken.getTokenAsync (/Users/deepak/workspace/personal/google-indexing-script/node_modules/gtoken/build/src/index.js:137:55)
    at GoogleToken.getToken (/Users/deepak/workspace/personal/google-indexing-script/node_modules/gtoken/build/src/index.js:96:21)
    at JWT.refreshTokenNoCache (/Users/deepak/workspace/personal/google-indexing-script/node_modules/google-auth-library/build/src/auth/jwtclient.js:165:36)
    at JWT.refreshToken (/Users/deepak/workspace/personal/google-indexing-script/node_modules/google-auth-library/build/src/auth/oauth2client.js:143:25)
    at JWT.authorizeAsync (/Users/deepak/workspace/personal/google-indexing-script/node_modules/google-auth-library/build/src/auth/jwtclient.js:146:35) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}
```

**Comment by mattogle1009-cell** [comment]
I have the same issue. Then, the strange point is that I'm using two laptop. But this issue is only in one laptop. 
Both are Win11/Node.JS 22.
